### ISSUE TITLE
Tiempo de computo

### ISSUE THREAD

**Issue by poveda-ruiz** [poveda-ruiz/MACH#11]
En la introducción ya hablamos de las ventajas que ofrece el nuevo método. Qué sucede con el tiempo de cómputo? Hay alguna desventaja en el nuevo método? En este sentido se debería resaltar como el nuevo método es efectivo evitando dos de las desventajas de los otros dos. No solo mostrar que es mejor porque el error relativo es menor.

Por ejemplo. una de las desventajas del método de velocidades es que de entrada se asume que los perfiles tienen la forma de un NFW. El nuevo método es como una mezcla de ambos, aunque se asume el perfil, se cuentan todas las partículas. En el paper de Ludlow (2012MNRAS.427.1322L, ver su párrafo 3 en la sección 2.2)  dicen que al pasar de c=2.5 a c = 5, la velocidad cambia muy poco, lo cual significa de manera inversa, que pequeños cambios de la velocidad, generan grandes cambios en la concentración.

Podríamos tal vez realizar la prueba con nuestro método vs. el método de velocidad y comprobar si dicha “desventaja” desaparece.  Entonces, en tu el archivo del test velocidades, podrías buscar aquellas que son “muy similares(tanto como lo dice Ludlow)” y escoger las de c=2.5 y c=5 (por ejemplo). Y entonces comparar dichos valores con el valor real de los MockHalos y el valor predicho por el nuevo método y graficarlo.

Para el método de densidad se podría hacer un ejercicio análogo. Mostrando explícitamente como varía “c” en función del tamaño (o numero de bin en la escala radial). Como se compara esa concentración con la “c” predicha por el nuevo método. 

De esta manera podrías tener dos plots que explícitamente demostraran las ventajas del método, además de la reducción del error relativo.

**Comment by forero** [comment]
Podrias aprovechar ahora las nuevas corridas en el cluster con emcee para medir tiempos e incluir algo sobre eso.

**Comment by forero** [comment]
Al final mediste algo sobre los tiempos?
