### ISSUE TITLE
Comentarios menores

### ISSUE THREAD

**Issue by poveda-ruiz** [poveda-ruiz/MACH#15]
Introducción.

Párrafo 1: “In the last three decades numerical experiments have made possible the simulation of dark matter dominated universes, yielding valuable insights on the large scale structure formation process as depicted in observations.” ——>  (e.g. Springel et al. 2006Natur.440.1137S)

Párrafo 2: “These profiles seem to be universal; independent of the cosmological parameters (Navarro, Frenk & White 1996, 1997) and self-similar“  ——>  (see Taylor y Navarro 2001, ApJ. 563,483 y las referencias ahí mostradas. Sin embargo, en Navarro et al. 2010 muestran que este no es el caso. Que no son estrictamente self-similar!)

app lied ——>  applied.  

Párrafo 3: Aparecen dos R con diferentes subíndice. R_V y R_v. Quizás se deberías definir el radio virial con un subíndice diferente (escribiendo explícitamente virial? o con una delta?), esto porque dicho radio no se menciona mucho en el texto, pero si aparecerán las variables “V” y “v (la minúscula, que es la velocidad normalizada)” y causa un poco de confusión.

Párrafo 4: ”With this promise a great deal of effort has been invested in calibrating this relationship with simulations but also finding the best possible way to constraint it with observations.” ——>  (Alguna cita?)

Párrafo 6: “The second problem is that, as in any process involving data binning, there is not an way to estimate the optimal bin size, which in turn can affect the results of the fit.”  ——>  (see Navarro et al. 2010 ?)

Sección 2.2. 

En la Eq. 2. el denominador dentro del argumento del logaritmo es r_s.

Sección 2.3.

La Eq. 6 debe ir después del primer párrafo. 

“It is possible to show that for the NFW profile the maximum is provided by”  ——>  “is given by” or “occurs at” (?)

“where xmax = 2.163…”  ——> Citar a Klypin (?)

Sección 3.

Tercer párrafo: ”As it was shown in the right panel of Figure (1) the circular velocity shows a maximum for all profiles with concentration values larger than c > 2.” ——> N es claro de la Figura 1 que la velocidad muestre un máximo solo para valores de c mayores a 2.

Párrafo 8:  “was randomly generated with a normal distribution centered around the last step with an standard deviation of sigma = 0.03.”  ——>  Alguna razón para esta sigma? (si no me equivoco es el mismo que el del paper contra el que comparamos)

Sección 4.1.

Párrafo 3: “Inside each group the halos have random concentration values in the range 1 < c < 20 with a flat distribution ——>  with a uniform distribution (?)

For all these halos with find   ——>  we find

“…We quantify the difference between the expected cin and obtained cout values by  Eq. 10” ——>  Thus, we define D as  Eq. 10. which quantify the difference between the expected cin and the obtained cout values. La sugerencia es porque se ve más ‘elegante’ terminar un párrafo con texto y no con una ecuación. Aunque esas son tonterías mías (Tomás).

Sección 4.1.2.

Si, sería interesante ver un plot, por ejemplo Cin vs. Cout para cada valor fijo de N.

Sección 4.1.3.

Primer Párrafo: “In the first case we use the same Metropolis-Hastings algorithm we have in our method to fit the density profile.” Como se definen los bins? Existe algún cambio notable en la Figura 3 para este método si aumenta el número de bins radiales?

Sección 4.2.

Segundo Párrafo: “Finally, for each FoF halo we select from all the particles that belong to it.” ——> we select all the particles that belong to it (?)

**Comment by forero** [comment]
¿Quien esta asignado?
