### ISSUE TITLE
Grafica para la seccion 4.1.2

### ISSUE THREAD

**Issue by forero** [poveda-ruiz/MACH#16]
Para la seccion 4.1.2 hace falta una grafica con los siguientes elementos.

Primero hay que seleccionar todos los halos ficticios que se crearon con N=20000 particulas. 
Luego hay que separar esa muestra en 4 sub-muestras de diferentes concentraciones: 2-6, 6-10, 10-14, 14-18.
Finalmente hay que preparar una grafica como la de la Figura 3 pero con esas nuevas 4 sub-muestras.

**Comment by forero** [comment]
Hola Christian, al final preparaste esta figura?

**Comment by poveda-ruiz** [comment]
Si! despues de 4 meses!
