### ISSUE TITLE
distribuciones no esfericas de particulas

### ISSUE THREAD

**Issue by forero** [poveda-ruiz/MACH#17]
Cuando las particulas del grupo FOF se cortan a una esfera de Rvir es posible que esa esfera no este totalmente contenida dentro del grupo FOF. Hay que cuantificar esto de alguna manera y mencionar la fraccion de casos en los que pasa.

**Comment by poveda-ruiz** [comment]
Tengo esto https://gist.github.com/poveda-ruiz/bd20b9cd144cb687da36 que calcula este momento de inercia http://mathworld.wolfram.com/images/equations/MomentofInertia/NumberedEquation2.gif y lo diagonaliza

**Comment by forero** [comment]
Es una primera aproximación, pero no responde realmente a la pregunta original.  Una esfera de particulas puede tener auto-valores diferentes del tensor de inercia si, por ejemplo, la distribucion de puntos cerca del centro es elipsoidal (justo como es el caso en los halos de las simulaciones).

**Comment by forero** [comment]
esto creo que lo podemos olvidar con los nuevos datos de la simulacion.
