### ISSUE TITLE
El enfoque bayesiano

### ISSUE THREAD

**Issue by poveda-ruiz** [poveda-ruiz/MACH#8]
En la introducción, en el último párrafo dice “…we present our new method to estimate the halo concentration, paying special attention to the Bayesian framework to find the most probable value and its uncertainty.”

Se debería hacer más énfasis en el enfoque bayesiano. Tomás sugiere dividir la Sección 3 en dos sub-secciones. La 3.1 (se puede llamar ‘three different approaches’). Dejando los tres primeros párrafos de la Sección 3. Después de donde dice “Multidark Simulation Suite.” Escribir unas dos o tres líneas describiendo el nuevo approach el cual se explicará con detalle a continuación.

Luego, en la subsección 3.2,  se debe detallar un poco más el método. Específicamente aclarar:

A).- El Metropolis-Hastings es un código desarrollado por nosotros y se debería hacer referencia a los programas y poner unas citas.

B).- Aunque el método Bayesiano esta ‘implícito’ en los cálculos. Nunca se vuelve a mencionar.

**Comment by forero** [comment]
Creo que nos podemos olvidar de este enfoque.
